name: Minecraft server

on:
  push:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Java JRE
      uses: actions/setup-java@v1.3.0
      with:
        # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
        java-version: 1.8
        # The package type (jre, jdk, jdk+fx)
        java-package: jre

    - uses: actions/checkout@v2
    - name: Setup server
      env:
        skfrp_username: ${{ secrets.skfrp_username }}
        skfrp_password: ${{ secrets.skfrp_password }}
        username: ${{ secrets.username }}
        email: ${{ secrets.email }}
        frpid: ${{ secrets.frpid }}
      run: |
        cd ~/work/MCGA/MCGA
        chmod 755 frp/frpc frp/frpc_origin server.sh
        #curl 'https://frp.tcotp.cn:4443/?version=2300&do=update'
        ./frp/frpc --su=$skfrp_username --sp=$skfrp_password --sid=14 --sc=${frpid} &
        ./frp/frpc_origin -c ./frp/frpc.ini &
        sudo mkdir /run/screen && sudo chmod 777 /run/screen
        ./server.sh start
        #sleep 1m
        sleep 352m
        ./server.sh stop
        sudo rm -f logs/*
        git config --global user.email $email
        git config --global user.name $username
        git add .
        git commit -m 'Update world'

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: $\{{ secrets.GITHUB_TOKEN }}
